ablate_mode: tile
batch_size: 32
block_type: normal
cols: 8
dataset: timit
dec_c_n_layers: 4
enc_n_layers: 3
freeze_num: 1
lambda_carrier_loss: 9.0
lambda_msg_loss: 1.0
load_ckpt: null
loss_type: mse
lr: 0.0015
max_batches: 10
message_file: /home/yyx/TIMIT/TRAIN/SA1.WAV.wav
mode: train
model_type: normal
n_pairs: 32
norm: instance
num_iters: 80
num_workers: 20
outdir: ablate_out
rows: 8
run_dir: /home/yyx/hideandspeak-log
sample_every: null
save_model_every: null
single: true
target: container
test_path: /home/yyx/TIMIT/TEST
train_path: /home/yyx/TIMIT/TRAIN
use_wandb: true
val_path: /home/yyx/TIMIT/VAL
